// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using monster_world.DBContext;

#nullable disable

namespace monster_world.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503191328_AddWorldSpawnsJson")]
    partial class AddWorldSpawnsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("monster_world.Models.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<Guid?>("InvoiceID")
                        .HasColumnType("uuid");

                    b.Property<bool>("Successful")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SuccessfulAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserBaseID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("UserBaseID");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("monster_world.Models.Invoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceType")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("monster_world.Models.Monster", b =>
                {
                    b.Property<int>("GlobalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GlobalID"));

                    b.Property<DateTime>("CaptureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HealTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsFighting")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Logs")
                        .HasColumnType("text[]");

                    b.Property<long>("OwnerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("GlobalID");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("monster_world.Models.Referral", b =>
                {
                    b.Property<Guid>("RefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<long[]>("Referrals")
                        .HasColumnType("bigint[]");

                    b.HasKey("RefID");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("monster_world.Models.UserBase", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<bool>("AllowsWriteToPm")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bonus")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Missions")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Monsters")
                        .HasColumnType("text[]");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<long>("ReferrerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBattles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCaptured")
                        .HasColumnType("integer");

                    b.Property<long>("TotalVictory")
                        .HasColumnType("bigint");

                    b.Property<List<string>>("Transactions")
                        .HasColumnType("text[]");

                    b.Property<bool>("Tutorial")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("UnlockedWorlds")
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("monster_world.Models.UserMission", b =>
                {
                    b.Property<Guid>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MissionId");

                    b.ToTable("UserMissions");
                });

            modelBuilder.Entity("monster_world.Models.UserOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("OfferId")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("monster_world.Models.Withdraw", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<bool>("Processing")
                        .HasColumnType("boolean");

                    b.Property<long?>("UserBaseID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserBaseID");

                    b.ToTable("Withdraws");
                });

            modelBuilder.Entity("monster_world.Models.WorldSpawns", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.HasKey("UserId");

                    b.ToTable("Spawns");
                });

            modelBuilder.Entity("monster_world.Services.BattleState", b =>
                {
                    b.Property<Guid>("BattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("EnemyActiveSkills")
                        .HasColumnType("text[]");

                    b.Property<string>("EnemyCooldownSkill")
                        .HasColumnType("text");

                    b.Property<string>("EnemyLastEffect")
                        .HasColumnType("text");

                    b.Property<int?>("EnemyMonsterGlobalID")
                        .HasColumnType("integer");

                    b.Property<List<string>>("PlayerActiveSkills")
                        .HasColumnType("text[]");

                    b.Property<string>("PlayerCooldownSkill")
                        .HasColumnType("text");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerLastEffect")
                        .HasColumnType("text");

                    b.Property<int?>("PlayerMonsterGlobalID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Victory")
                        .HasColumnType("boolean");

                    b.HasKey("BattleId");

                    b.HasIndex("EnemyMonsterGlobalID");

                    b.HasIndex("PlayerMonsterGlobalID");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("monster_world.Models.Deposit", b =>
                {
                    b.HasOne("monster_world.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceID");

                    b.HasOne("monster_world.Models.UserBase", null)
                        .WithMany("Deposits")
                        .HasForeignKey("UserBaseID");

                    b.OwnsOne("monster_world.Models.Balance", "Balance", b1 =>
                        {
                            b1.Property<Guid>("DepositId")
                                .HasColumnType("uuid");

                            b1.Property<double>("CRYSTAL")
                                .HasColumnType("double precision");

                            b1.Property<double>("GOLD")
                                .HasColumnType("double precision");

                            b1.Property<double>("TON")
                                .HasColumnType("double precision");

                            b1.HasKey("DepositId");

                            b1.ToTable("Deposits");

                            b1.WithOwner()
                                .HasForeignKey("DepositId");
                        });

                    b.Navigation("Balance");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("monster_world.Models.UserBase", b =>
                {
                    b.OwnsOne("monster_world.Models.Items", "Items", b1 =>
                        {
                            b1.Property<long>("UserBaseID")
                                .HasColumnType("bigint");

                            b1.Property<int>("AvalancheSpell")
                                .HasColumnType("integer");

                            b1.Property<int>("DarkSpell")
                                .HasColumnType("integer");

                            b1.Property<int>("Hallucinogen")
                                .HasColumnType("integer");

                            b1.Property<int>("HealSpell")
                                .HasColumnType("integer");

                            b1.Property<int>("LavaSpell")
                                .HasColumnType("integer");

                            b1.Property<int>("MonstaBall")
                                .HasColumnType("integer");

                            b1.Property<int>("Poison")
                                .HasColumnType("integer");

                            b1.Property<int>("RagePotion")
                                .HasColumnType("integer");

                            b1.Property<int>("Shield")
                                .HasColumnType("integer");

                            b1.Property<int>("ThunderSpell")
                                .HasColumnType("integer");

                            b1.Property<int>("WaterFallSpell")
                                .HasColumnType("integer");

                            b1.Property<int>("WindSpell")
                                .HasColumnType("integer");

                            b1.HasKey("UserBaseID");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserBaseID");
                        });

                    b.OwnsOne("monster_world.Models.Balance", "Balance", b1 =>
                        {
                            b1.Property<long>("UserBaseID")
                                .HasColumnType("bigint");

                            b1.Property<double>("CRYSTAL")
                                .HasColumnType("double precision");

                            b1.Property<double>("GOLD")
                                .HasColumnType("double precision");

                            b1.Property<double>("TON")
                                .HasColumnType("double precision");

                            b1.HasKey("UserBaseID");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserBaseID");
                        });

                    b.Navigation("Balance");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("monster_world.Models.UserOffer", b =>
                {
                    b.HasOne("monster_world.Models.UserBase", "User")
                        .WithMany("OffersPurchased")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("monster_world.Models.Withdraw", b =>
                {
                    b.HasOne("monster_world.Models.UserBase", null)
                        .WithMany("Withdraws")
                        .HasForeignKey("UserBaseID");
                });

            modelBuilder.Entity("monster_world.Models.WorldSpawns", b =>
                {
                    b.OwnsMany("monster_world.Models.Location", "Spawns", b1 =>
                        {
                            b1.Property<long>("WorldSpawnsUserId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateTime>("LastSpawned")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<List<string>>("Nodes")
                                .HasColumnType("text[]");

                            b1.Property<string>("World")
                                .HasColumnType("text");

                            b1.HasKey("WorldSpawnsUserId", "Id");

                            b1.ToTable("Spawns");

                            b1.ToJson("Spawns");

                            b1.WithOwner()
                                .HasForeignKey("WorldSpawnsUserId");
                        });

                    b.Navigation("Spawns");
                });

            modelBuilder.Entity("monster_world.Services.BattleState", b =>
                {
                    b.HasOne("monster_world.Models.Monster", "EnemyMonster")
                        .WithMany()
                        .HasForeignKey("EnemyMonsterGlobalID");

                    b.HasOne("monster_world.Models.Monster", "PlayerMonster")
                        .WithMany()
                        .HasForeignKey("PlayerMonsterGlobalID");

                    b.OwnsOne("monster_world.Services.MonsterState", "EnemyState", b1 =>
                        {
                            b1.Property<Guid>("BattleStateBattleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AimBonus")
                                .HasColumnType("integer");

                            b1.Property<int>("AtkBonus")
                                .HasColumnType("integer");

                            b1.Property<int>("DefBonus")
                                .HasColumnType("integer");

                            b1.Property<bool>("Hypno")
                                .HasColumnType("boolean");

                            b1.Property<bool>("JustMissed")
                                .HasColumnType("boolean");

                            b1.Property<int>("PendingHeal")
                                .HasColumnType("integer");

                            b1.Property<bool>("Rage")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Sick")
                                .HasColumnType("boolean");

                            b1.HasKey("BattleStateBattleId");

                            b1.ToTable("Battles");

                            b1.WithOwner()
                                .HasForeignKey("BattleStateBattleId");
                        });

                    b.OwnsOne("monster_world.Services.MonsterState", "PlayerState", b1 =>
                        {
                            b1.Property<Guid>("BattleStateBattleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AimBonus")
                                .HasColumnType("integer");

                            b1.Property<int>("AtkBonus")
                                .HasColumnType("integer");

                            b1.Property<int>("DefBonus")
                                .HasColumnType("integer");

                            b1.Property<bool>("Hypno")
                                .HasColumnType("boolean");

                            b1.Property<bool>("JustMissed")
                                .HasColumnType("boolean");

                            b1.Property<int>("PendingHeal")
                                .HasColumnType("integer");

                            b1.Property<bool>("Rage")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Sick")
                                .HasColumnType("boolean");

                            b1.HasKey("BattleStateBattleId");

                            b1.ToTable("Battles");

                            b1.WithOwner()
                                .HasForeignKey("BattleStateBattleId");
                        });

                    b.Navigation("EnemyMonster");

                    b.Navigation("EnemyState");

                    b.Navigation("PlayerMonster");

                    b.Navigation("PlayerState");
                });

            modelBuilder.Entity("monster_world.Models.UserBase", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("OffersPurchased");

                    b.Navigation("Withdraws");
                });
#pragma warning restore 612, 618
        }
    }
}
